pipeline:
  production-push:
    image: plugins/docker
    repo: $${{REGISTRY_ADDR}}/badnews
    registry: $${{REGISTRY_ADDR}}
    tags: [ latest ]
    secrets: [ docker_password, registry_addr, docker_username ]
    when:
      branch: master

  