pipeline:
  production-push:
    image: docker
    commands:
      - docker login $${{REGISTRY_ADDR}} -u ${{DOCKER_PASSWORD}} -u $${{DOCKER_USERNAME}}
      - docker build . -t $${{REGISTRY_ADDR}}/badnews:latest
      - docker push $${{REGISTRY_ADDR}}/badnews:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ docker_password, registry_addr, docker_username ]
    when:
      branch: master

  